### PR TITLE
Add FEM convection kernel 

### PR DESCRIPTION
**Pull request by artv3**

### CODE REVIEW

**Review by MrBurmark — APPROVED** [review]

**Comment by artv3** [comment]
TODO: replace kernel bodies with macros, and fix memory error.

**Review by rhornung67 — APPROVED** [review]

**Comment by artv3** [comment]
I think one of our test is down, there is an error unrelated to this PR.

**Comment by rhornung67** [comment]
Looks like ruby is offline, updates?

**Comment by artv3** [comment]
> Looks like ruby is offline, updates?

I just restarted the job, I'll keep an eye on it. Hopefully its back up by this week.

**Pull request merged**
