### PR TITLE
PR from fork/333

### PR DESCRIPTION
**Pull request by MichaelMcKinsey1**
See #333

### CODE REVIEW

**Comment by MichaelMcKinsey1** [comment]
@MrBurmark I'm guessing tests failed because of TOSS4 update? For example, ruby doesn't have that old gcc version anymore
```
     Versions:
        gcc/10.3.1-magic
        gcc/10.3.1
        gcc/11.2.1-magic
        gcc/11.2.1
        gcc/12.1.1-magic
        gcc/12.1.1
```
Where catalyst (TOSS3) does
```
     Versions:
        gcc/4.8-redhat
        gcc/4.9.3
        gcc/6.1.0
        gcc/7.1.0
        gcc/7.3.0
        gcc/8.1.0
        gcc/8.3.1
        gcc/9.3.1
        gcc/10.2.1
```

**Comment by rhornung67** [comment]
I think @adrienbernede has this fixed in a PR. Maybe this one? https://github.com/LLNL/RAJAPerf/pull/329. We pulled in the needed changes to RAJA and then RAJAPerf has to update to RAJA develop for everything to work.

**Comment by adrienbernede** [comment]
There was some long due CI update in https://github.com/LLNL/RAJAPerf/pull/254.
https://github.com/LLNL/RAJAPerf/pull/329 is the fix for RHEL 8, that is done on top of the former.
254 has been reviewed and approved.
To my understanding only the CI issues were holding that PR.
I still have some intermittent failures though... working on that.

**Comment by rhornung67** [comment]
@MichaelMcKinsey1 if we merge https://github.com/LLNL/RAJAPerf/pull/254 into RAJAPerf develop, will that disrupt your work?

**Comment by MichaelMcKinsey1** [comment]
> @MichaelMcKinsey1 if we merge #254 into RAJAPerf develop, will that disrupt your work?

It shouldn't disrupt this PR, but #331 is directly conflicting with #254; it is a variant of the same work. I think we should discuss this Tuesday.

**Comment by rhornung67** [comment]
> > @MichaelMcKinsey1 if we merge #254 into RAJAPerf develop, will that disrupt your work?
> 
> It shouldn't disrupt this PR, but #331 is directly conflicting with #254; it is a variant of the same work. I think we should discuss this Tuesday in the RAJA meeting.

OK. ruby tests will continue to fail because changes for the RHEL8 upgrade are planned to come through #254. We may have to rethink the merge sequence. We need more traffic signals I think.... 😄

**Review by MrBurmark — APPROVED** [review]

**Comment by MichaelMcKinsey1** [comment]
@MrBurmark @rhornung67 Passing CI

**Comment by rhornung67** [comment]
Excellent! I've been shepherding things along. LC platforms have been plugged up lately.

**Comment by rhornung67** [comment]
@MichaelMcKinsey1 are you aware of this one?

**Comment by MichaelMcKinsey1** [comment]
> @MichaelMcKinsey1 are you aware of this one? #348

Is #348 the one we are merging?

**Comment by rhornung67** [comment]
I believe so. I need to confirm with @adrienbernede

**Comment by rhornung67** [comment]
@MichaelMcKinsey1 I merged develop into this. When CI checks are all green, let's go ahead and merge this one.

**Comment by MichaelMcKinsey1** [comment]
Looks like dev failing on the same tests

**Comment by rhornung67** [comment]
tioga jobs timing out in the queue due to heavy system use. jobs restared.

**Review by rhornung67 — APPROVED** [review]
@MichaelMcKinsey1 CI checks are green on this one. Please feel free to merge.

**Comment by MichaelMcKinsey1** [comment]
@rhornung67 GitHub is saying I'm not authorized to merge.

**Pull request merged**
