### PR TITLE
Feature/omp lambda

### PR DESCRIPTION
**Pull request by rhornung67**
This PR includes some code cleanup and refactoring to share lambda objects among CPU variants. The intent is to prepare for a new OpenMP-lambda variant that will be coming in a future PR.

### CODE REVIEW

**Comment by davidbeckingsale** [comment]
Is there a performance difference between this branch and master? We should capture that before merging.

**Comment by rhornung67** [comment]
I did some preliminary tests and didn't see much of a difference and it varied across runs.  I can do some more detailed testing tomorrow and report back.

**Comment by davidbeckingsale** [comment]
Okay, that sounds good. I don't think it matters too much either way, it's just a good idea to document it somewhere.

**Comment by rhornung67** [comment]
@davidbeckingsale ran tests with gnu, clang, and intel compilers comparing these changes against develop. It appears that any performance differences are within the bounds of run-to-run variations.

**Pull request merged**
