### PR TITLE
Vol3d update

### PR DESCRIPTION
**Pull request by mcordery**
Updated scripts/host configs for 11/10 drop of clang. 
VOL3D seems to work but please check.

### CODE REVIEW

**Comment by rhornung67** [comment]
@mcordery not sure what's going on with this PR. I tried a few build scripts that work with the develop branch and the one I'm working on, but I could not get anything using omp target to compile.  Also, I pushed a couple of commits to this branch that fixed some issues (code commented out that shouldn't have been, broken scripts, etc.)

**Comment by jonesholger** [comment]
Most likely Matt is using the latest compiler drops.. I'll check it out
first thing tomorrow.

**Comment by mcordery** [comment]
Pretty much using the 11/10 compiler drop of clang.  I can sync up with Holger on this to see what the problem is.

**Comment by jonesholger** [comment]
It's fine with the 10/13  blueos_nvcc9.0_clang-coral-2017.10.13_omptarget.sh

I'll try a newer script.

**Comment by jonesholger** [comment]
Fails with  ./scripts/blueos_clang-coral-2017.11.10.sh. I'll keep digging

ar: /usr/bin/ar: File format not recognized
error: 1 extracting the archived object files failed.
nvlink fatal   : Could not open input file '/var/tmp/holger/libRAJA-1e206f.o'

**Comment by mcordery** [comment]
That's weird, I didn't see that
 
----- Original message -----From: jonesholger <notifications@github.com>To: LLNL/RAJAPerf <RAJAPerf@noreply.github.com>Cc: Matthew Cordery <cordery1@llnl.gov>, Mention <mention@noreply.github.com>Subject: Re: [LLNL/RAJAPerf] Vol3d update (#8)Date: Mon, Nov 27, 2017 10:55 AM 
Fails with ./scripts/blueos_clang-coral-2017.11.10.sh. I'll keep digging
ar: /usr/bin/ar: File format not recognizederror: 1 extracting the archived object files failed.nvlink fatal : Could not open input file '/var/tmp/holger/libRAJA-1e206f.o'

**Comment by jonesholger** [comment]
So far I'm just seeing issues with the 11/10 drop (maybe not ready for prime time). Some of the older clang-coral scripts may also need to change as they don't run omp-target, even though parts of the script look like it's intended. We'll have to settle on whether clang-coral automatically implies omp-target. But, I'll have to do a fresh checkout as I have too much of my own stuff around.

Matt remind me why did you jump to the 11/10 drop.

**Comment by jonesholger** [comment]
Anyway for the VOL3D update it looks fine, but we have other issues that maybe don't belong to this PR.

**Comment by rhornung67** [comment]
@jonesholger @mcordery let's sort out the host-config files we want to keep and use at tomorrow's meeting. It's probably not worth it to keep things for older clang coral compilers, unless we see performance degradation for newer ones.

**Comment by mcordery** [comment]
The only reason would be newer versions generally fix issues. Let me take a look at it again.
 
----- Original message -----From: jonesholger <notifications@github.com>To: LLNL/RAJAPerf <RAJAPerf@noreply.github.com>Cc: Matthew Cordery <cordery1@llnl.gov>, Mention <mention@noreply.github.com>Subject: Re: [LLNL/RAJAPerf] Vol3d update (#8)Date: Mon, Nov 27, 2017 11:36 AM 
So far I'm just seeing issues with the 11/10 drop (maybe not ready for prime time). Some of the older clang-coral scripts may also need to change as they don't run omp-target, even though parts of the script look like it's intended. We'll have to settle on whether clang-coral automatically implies omp-target. But, I'll have to do a fresh checkout as I have too much of my own stuff around.
Matt remind me why did you jump to the 11/10 drop.

**Comment by jonesholger** [comment]
@mcordery I think you can close this PR

**Pull request closed without merging**
