### PR TITLE
Update checksum weighing

### LINKED ISSUE #237: Think about how checksum should weigh elements in arrays.
Currently calcChecksum weights each element proportionally to its position relative to the start of the array. So later elements are given more weight and the total sum is proportional to the number of elements squared.
```cpp
long double tchk = 0.0;
for (Index_type j = 0; j < len; ++j) {
  tchk += (j+1)*ptr[j]*scale_factor;
}
```
I ran into issues with the checksum when implementing scan kernels with doubles as the error at each element is proportional to its position relative to the start of the array. I worked around this by setting the checksum scale factor to be inversely proportional to the problem size squared.
What do people think about changing the way we weigh elements in arrays so they are treated more equally?

### PR DESCRIPTION
**Pull request by MrBurmark**
# Update checksum weighing

Use more uniform weighing when calculating checksums to avoid weighing early or late elements more heavily.
Use kahan sum to reduce error when calculating the checksum.

- This PR is a feature
- It does the following (modify list as needed):
  - Fixes #237 
  - Adds better checksums at the request of me and Rich

### CODE REVIEW

**Comment by MrBurmark** [comment]
The time to run daxpy is about 0.24s for sequential on rznevada.

**Comment by rhornung67** [comment]
> The time to run daxpy is about 0.24s for sequential on rznevada.

So about 14% of total time for checksum (up from ~0.7% from what we have now). That's more of an increase than I would expect. What do you think?

**Comment by artv3** [comment]
@MrBurmark everything still passes right?

**Comment by rhornung67** [comment]
@artv3 I haven't run it, but everything should pass. The advantage to having a new checksum calculation is more even treatment of all entries in the results vector(s) and potentially easier to normalize the checksums across all kernels.

**Comment by MrBurmark** [comment]
Entire runtimes.
original: 3m23.283s
unweighed-kahan: 3m26.381s
sin-weighed-kahan: 3m34.502s

**Comment by MrBurmark** [comment]
Yes everything still passes.

**Review by artv3 — APPROVED** [review]

**Review by rhornung67 — APPROVED** [review]
I ran some tests with this locally on multiple machines and compilers. Overall, checksum diffs are much smaller now. However, there are a few kernels where it doesn't change things much.

**Pull request merged**
