### PR TITLE
Merge develop into master for v.0.3.0 release

### PR DESCRIPTION
**Pull request by rhornung67**

### CODE REVIEW

**Comment by rhornung67** [comment]
@davidbeckingsale no, just tags. is there a better way?

**Comment by davidbeckingsale** [comment]
Tags is great. I just wondered if you had release number in a file somewhere and hadn't updated it. This looks good.

**Comment by rhornung67** [comment]
Dang. You remind me that I forgot to update the release number in the CMakeLists.txt file. D'oh!...
Another PR with a minor change coming....

**Comment by davidbeckingsale** [comment]
😞 whoops! I wish there was a better way to deal with this.

**Pull request closed without merging**
