### PR TITLE
Reorg GPU kernel error checks

### PR DESCRIPTION
**Pull request by rhornung67**
# Summary 

- This PR...

### CODE REVIEW

**Comment by rhornung67** [comment]
@MrBurmark please take a peek at the DAXPY kernel changes and let me know if this is what you had in mind. If you're good with it, I will change all the otheres.

**Comment by MrBurmark** [comment]
Yep that looks good to me.

**Comment by rhornung67** [comment]
@MrBurmark @artv3 this should be good to merge when all non-tioga checks come back green. I manually tested on rzvernal. tioga is flaky today.

**Comment by rhornung67** [comment]
@MrBurmark @artv3 this is good to merge.

**Review by MrBurmark — APPROVED** [review]

**Pull request merged**
