### PR TITLE
Woptim/share raja perf package

### PR DESCRIPTION
**Pull request by adrienbernede**
## Summary

Working on moving RAJAPerf to RADIUSS Spack Config (RAD_SConf)

Here is the process, with the merge sequence:

    I created a PR in RAD_SConf with new RAJA_Perf package,
    I used @main as a base branch, which has new rocmcc, which will force we to update Radiuss Shared CI (RAD_SCI) to v2023.03.0rc
    I created a PR in RAJA with new RAD_SConf (with raja_perf package) and update RAD_SCI@v2023.03.0rc as well as CI local config
    I created a PR in RAJAPerf with new RAJA (with new RAD_SConf (with raja_perf package) an RAD_SCI) and removed local RAJA_Perf package and pointed uberenv at RAD_SConf/packages in RAJA tpl.
    I also update RAD_SCI and local CI config.

Once test pass:

    [DONE] Merge PR in RAD_SCI@main
    [DONE] Update PR in RAJA to point to new [RAD_SCI@main]
    [NOW] Merge PR in RAJA@develop
    [THIS ]Update PR in RAJA_Perf to point to new [RAJA@develop]
    Merge PR in RAJA_Perf

## Notes

In order to move the RAJAPerf Spack package to Radiuss-Spack-Configs, we had to merge that change in Radiuss-Spack-Configs main branch, then merge it to RAJA (https://github.com/LLNL/RAJA/pull/1457) (which also required to update Radiuss-Shared-CI), and finally to here we are.

## Before we merge

We need to merge https://github.com/LLNL/RAJA/pull/1457 first, and then point tpl/RAJA at the latest develop.

### CODE REVIEW

**Comment by adrienbernede** [comment]
Once https://github.com/LLNL/RAJA/pull/1457 is merged, I will update the tpl/RAJA submodule and this PR will be ready.

**Comment by rhornung67** [comment]
@adrienbernede why didn't tioga CI run on this?

**Review by rhornung67 — APPROVED** [review]

**Comment by adrienbernede** [comment]
@rhornung67 RAJAPerf CI does not have Tioga set. I can add it.

**Comment by rhornung67** [comment]
I thought it was using the same specs as the RAJA submodule?

**Pull request merged**
