### PR TITLE
Rhel8 update

### PR DESCRIPTION
**Pull request by rhornung67**
# Summary 

- This PR pulls branch https://github.com/LLNL/RAJAPerf/tree/woptim/rhel-8-update into develop so we can get GitLab CI working again, merge PRs, and work toward a release.

### CODE REVIEW

**Comment by MrBurmark** [comment]
@rhornung67 Is this supposed to have the caliper changes?

**Comment by rhornung67** [comment]
> @rhornung67 Is this supposed to have the caliper changes?

I turned those off due to some spack issue that I couldn't resolve. They are still in another PR related to the caliper integration. My preference is to get the CI running so we can re-start PR merges.

**Comment by rhornung67** [comment]
Closing. I didn't realize that there was a bunch of Caliper related stuff in the branch that is not what we wanted.

**Comment by adrienbernede** [comment]
@rhornung67 , to follow up with our conversation, it looks like you would like to have only the CI changes here.

I'll try to get that for you asap.

**Pull request closed without merging**
