### PR TITLE
Feature/rhornung67/newkernels

### PR DESCRIPTION
**Pull request by rhornung67**
Reworked LTIMES based on conversations with Adam and filled in missing variants.

Strictly using forallN for now and added macros to switch to RAJA::nested and assess as more
functionality comes on line.

### CODE REVIEW

**Comment by jonesholger** [comment]
put a #if 0 around the USE_FORALLN defines, in order to test out the nested variants but am having trouble compiling the LTIMES kernel. 

 error: no instance of function template "camp::invoke" matches the argument list. 

submodule 
RAJA is at https://github.com/LLNL/RAJA/commit/2394c05f4d2e7c6853db584f34193519befc79a5

I'll checkout RAJA develop explicitly, pull and try again.

**Comment by rhornung67** [comment]
@jonesholger the 'nested' variants work in the NESTED_INIT kernel but not in LTIMES. I talked to Tom about this last week and he pushed a fix (hopefully) over the weekend. I have to change some code to make it work, I think.  If I get it to work, I'll let you know.

BTW, there are #defines at the top of the KernelBase.hpp file that you can use to switch between forallN and nested.

**Comment by jonesholger** [comment]
Yep,  I recall the convo regarding TypedRangeSegments.  I'll check back later.

**Comment by rhornung67** [comment]
@jonesholger the RAJA::nested kernels work with Tom's changes and I have them on by default for seq and openmp policies.  If you approve, I'll merge this. I'm going to tackle some code cleanup and restructuring next.

**Pull request merged**
