### PR TITLE
Fix CI for Caliper integration branch

### PR DESCRIPTION
**Pull request by adrienbernede**
### In this PR

- Update Radiuss-Shared-CI
- Update RAJA submodule (which updates Radiuss-Spack-Configs too)
- Add a +caliper CI job

### CODE REVIEW

**Comment by adrienbernede** [comment]
@rhornung67 @jonesholger, this is a suggested fix for the caliper integration branch.

Note that an important subsequent step will be to address Spack packages updates as described in #287.
Since the CI is passing as-is, I am going to focus on some other tasks first.

**Comment by adrienbernede** [comment]
Reminder: this is targeting #254.

**Review by rhornung67 — APPROVED** [review]

**Comment by rhornung67** [comment]
@adrienbernede do you have permissions to merge this, or should I do it?

**Comment by adrienbernede** [comment]
I have, but was waiting for your approval.

**Pull request merged**
