### PR TITLE
Fix omp target build

### LINKED ISSUE #104: HALOEXCHANGE-OMPTarget references non-existent omp_target_parallel_exec policy
Trying to build the OpenMP Target version with the Cray Clang compiler, compilation fails during the HALOEXCHANGE app:

```
[  4%] Building CXX object src/CMakeFiles/raja-perf-omptarget.exe.dir/apps/HALOEXCHANGE-OMPTarget.cpp.o
/home/users/sabbott/nightly_crons/rajaperf-openmp-gfx906/RAJAPerf/src/apps/HALOEXCHANGE-OMPTarget.cpp:101:28: error: no type named 'omp_target_parallel_exec' in namespace 'RAJA'; did you mean 'omp_target_parallel_for_exec_nt'?
    using EXEC_POL = RAJA::omp_target_parallel_exec;
                     ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
                           omp_target_parallel_for_exec_nt
/home/users/sabbott/nightly_crons/rajaperf-openmp-gfx906/RAJAPerf/tpl/RAJA/include/RAJA/policy/openmp_target/policy.hpp:79:20: note: 'omp_target_parallel_for_exec_nt' declared here
using policy::omp::omp_target_parallel_for_exec_nt;
                   ^
1 error generated.
```
This line seems to be at fault:

https://github.com/LLNL/RAJAPerf/blob/5f37acca141b52344a9916f6cb95c606287f0032/src/apps/HALOEXCHANGE-OMPTarget.cpp#L101

Changing that to the compiler-recommended `omp_target_parallel_for_exec_nt` does work.

For the record, I'm configuring with:
```
cmake \
         -DENABLE_ALL_WARNINGS=Off \
         -DENABLE_OPENMP=On \
         -DENABLE_TARGET_OPENMP=On \
         -DENABLE_CUDA=Off \
         -DENABLE_CLANG_CUDA=Off \
         -DENABLE_HIP=Off \
         -DENABLE_CLANG_HIP=Off \
         -DENABLE_TBB=Off \
         -DCMAKE_CXX_COMPILER=CC \
         -DCMAKE_C_COMPILER=cc \
         -DCMAKE_BUILD_TYPE=Release \
         -DCMAKE_CXX_STANDARD=c++11 \
         -DENABLE_TESTS=Off \
         -DENABLE_EXAMPLES=Off ../
```

### PR DESCRIPTION
**Pull request by MrBurmark**
Fix a policy used in the halo exchange test.

Fixes #104

### CODE REVIEW

**Review by rhornung67 — APPROVED** [review]
Thanks @MrBurmark !

**Comment by abbotts** [comment]
Thanks for the quick fix! I can confirm that this builds with CCE Offloading and runs the OpenMP Target Offload variants.

The base sequential variant doesn't run, but I think that's unrelated to the content of this PR.

**Comment by MrBurmark** [comment]
> The base sequential variant doesn't run, but I think that's unrelated to the content of this PR.

Let me see if I can see what's going on there.

**Comment by rhornung67** [comment]
Thanks @MrBurmark

**Comment by MrBurmark** [comment]
Hmm, it doesn't look like any of the Base_Seq variants are running when we build for omp target.

**Comment by abbotts** [comment]
@MrBurmark , if I remove `-DRUN_RAJA_SEQ` from the `remove_definitions` command then the Base_Seq variants run.

https://github.com/LLNL/RAJAPerf/blob/e31d86a74125f03cb2171b376fc0320d59008227/src/CMakeLists.txt#L30

(of course, the RAJA_Seq and also Lambda_Seq variants then also run). In all the places I've looked, however, the `RUN_RAJA_SEQ` preprocessor logic looks sound.

**Comment by abbotts** [comment]
@MrBurmark , I opened #106 ; the problem seems to be some fall through case evaluations. I haven't looked at the other logic in that function to see if a similar problem can occur in different situations.

**Pull request merged**
