### PR TITLE
FLOPs per rep

### PR DESCRIPTION
**Pull request by MrBurmark**
Add FLOPs per rep, with FLOP generously meaning anything from an add to multiply, to a divide, sqrt, or exponential.

### CODE REVIEW

**Comment by artv3** [comment]
Out of curiosity have you compared with what nvprof reports for flops? To see if the numbers are close?

**Review by rhornung67 — COMMENTED** [review]
I believe this looks OK. It may be a good idea for a small group of us to walk through changes like this to see if we agree on the flop counts.  Also, we should sequence PRs like this to avoid massive merge conflicts. I'm re-working the problem size and its per rep stuff.

**Review by rhornung67 — APPROVED** [review]
I'll approve now. We can get more eyeballs on it later. I'll wait until this is merged before I finish my rework changes.

**Comment by MrBurmark** [comment]
You're right about merge conflicts. I probably should have waited, but I had some free energy last night so I just jumped into this.

**Comment by MrBurmark** [comment]
@artv3 That's a good idea, let me do a quick sanity check with nsight.

**Review by artv3 — APPROVED** [review]

**Pull request merged**
