### PR TITLE
update submodules so everything points to stuff that works

### PR DESCRIPTION
**Pull request by rhornung67**

### CODE REVIEW

**Comment by jonesholger** [comment]
Looks like RAJA is parked at bash-4.2$ git log
commit b89a813498e7360452f59fe7f7874079721a2c39

which is 13 commits behind release 0.5.2,  so thinking we should update, but don't know for sure

**Comment by rhornung67** [comment]
After the 0.5.2 release stufff is merged, I will update the submodules in the perf suite.

**Comment by jonesholger** [comment]
sounds good!

**Comment by rhornung67** [comment]
@jonesholger I addressed your requested changes. When this passes, it should be good to merge.

**Comment by rhornung67** [comment]
@davidbeckingsale this release will be pinned to RAJA v0.5.2 and BLT version used by that release of RAJA.

**Pull request merged**
