### PR TITLE
[Woptim] Shared CI

### PR DESCRIPTION
**Pull request by adrienbernede**
### Summary: Move Gitlab CI to RADIUSS Shared CI config.

- This PR is a refactoring of Gitlab CI config.
- It does the following:
  - refactors CI config
  - updates some CI specs to match RAJA CI

Tests are now passing. However, **do not merge until**:
- [x] clean the remaining naming suggestions by @kab163 : e.g. clang@9 -> clang@9.0.0 which requires an update in radiuss-shared-ci
- [x] filter out duplicated specs (update xl to 16.1.1.12 in radiuss shared CI and remove xl@16.1.1.11 jobs).
- [x] restore some jobs to there original spec (I had updated some of them (cuda version typically) to match RAJA ones, but will follow @rhornung67 suggestion here instead: https://github.com/LLNL/RAJAPerf/pull/261#issuecomment-1235647434)
- [x] test updating to spack@0.18.1 -> Turns out we need newer Uberenv (quote issue).
- [x] test pointing to RAJA@woptim/shared-ci: doing this will ensure we won’t have an issue when we merge https://github.com/LLNL/RAJA/pull/1308. -> This is actually necessary to pass tests with spack@0.18.1. We need to merge shared CI in RAJA first, and then update tpl/RAJA to new develop.

The above should be quick, but requires a little sync with https://github.com/LLNL/Umpire/pull/780 and https://github.com/LLNL/RAJA/pull/1308

### CODE REVIEW

**Comment by adrienbernede** [comment]
Note: xl.16.1.1.11 jobs expected to fail: shared config missing crucial flags.
xl.16.1.1.12 jobs should be ok.

**Comment by adrienbernede** [comment]
Note: I have been considering pointing to RAJA CI files directly to avoid duplication. Unfortunately it is not possible to include files from a git submodule in CI.
It is possible to point to the files from the RAJA repo itself, but we would have to ensure somehow that we are using the same ref as in the submodule.

**Comment by adrienbernede** [comment]
@rhornung67 @kab163 We should get this merged: it’s been ready for a while and is in sync with the changes made in https://github.com/LLNL/Umpire/pull/780 and https://github.com/LLNL/RAJA/pull/1308.

**Comment by rhornung67** [comment]
@adrienbernede this is good timing. i'm working on other updates to RAJAPerf. https://github.com/LLNL/RAJA/pull/1308 has been merged. Does this PR include the RAJA submodule with those changes?

**Review by rhornung67 — APPROVED** [review]
Thank you @adrienbernede

**Pull request merged**
