### PR TITLE
Fixes: Cmake fails in container as BLT component is missing

### PR DESCRIPTION
**Pull request by rhornung67**
# This PR pulls in a PR branch from a fork into the repo for testing and review

- Original PR is: https://github.com/LLNL/RAJAPerf/pull/303

### CODE REVIEW

**Comment by rhornung67** [comment]
@mdavis36 should we add the command to update git submodules recursively to all jobs in the Dockerfile?

**Review by MrBurmark — APPROVED** [review]

**Comment by mdavis36** [comment]
It is typically assumed that submodules should be correctly configured before running docker, that's why we `COPY .` local files into the workspace. This could cause issues if you are using docker to do development locally and you have unstaged changes in one of the submodules.

**Comment by rhornung67** [comment]
So we shouldn't add the git submodule update command to the Dockerfile at all, right? You just have to use docker correctly.

**Comment by mdavis36** [comment]
@rhornung67 I would vote against it. Users should run `git submodule update` before doing any docker builds since this is used as a more flexible development container.

**Comment by rhornung67** [comment]
Thanks @mdavis.

@asarkar-parsys Based on the discussion here, were going to close this PR without merging. Do you understand how to avoid the issue in the future?

**Comment by asarkar-parsys** [comment]
Yes, I think that makes sense. I think the submodules should be pulled before the workspace is copied in.

**Pull request closed without merging**
