### PR TITLE
Fix/reduce3 int kokkos namespace

### PR DESCRIPTION
**Pull request by ajpowelsnl**
@MrBurmark , @davidbeckingsale -- Apologies for having two pull requests (PR) in play at one time, but an update to Kokkos broke `REDUCE3_INT-Kokkos.`  This PR removes the `Experimental` namespace for `Kokkos::Min` and `Kokkos::Max` routines.  This fix will be required (i.e., it must precede) for PR #256.

At the root directory level, please update dependencies by issuing this command:

```
git submodule update --init --recursive
```

To configure the build for the Kokkos variants in RAJAPerf Suite, please issue the following CMake command:

```
# Kokkos Cuda build
cmake \
-DENABLE_KOKKOS=ON \
-DRAJA_PERFSUITE_ENABLE_TESTS=OFF \
-DCUDA_ARCH=sm_70 \
-DENABLE_CUDA=ON \
-DKokkos_ARCH_VOLTA70=ON \
-DCMAKE_CUDA_ARCHITECTURES=70 \
-DCMAKE_BUILD_TYPE=Release .. \
```

To build:

```
make -j24
```

### CODE REVIEW

**Review by artv3 — APPROVED** [review]

**Comment by ajpowelsnl** [comment]
Hi @artv3 -- Would you please retest?  It would appear that the CI failures are Docker-specific (?).  I have clang-formatted the changed file.  Please do let me know if I'm not interpreting these failures correctly.

**Review by MrBurmark — APPROVED** [review]

**Comment by ajpowelsnl** [comment]
@MrBurmark and @artv3 -- would you please retest this PR (I updated with changes to your `develop`)?

**Review by MrBurmark — APPROVED** [review]

**Comment by artv3** [comment]
Looks like testing is in progress.

**Comment by ajpowelsnl** [comment]
> Looks like testing is in progress.

Thanks, guys!

**Comment by ajpowelsnl** [comment]
@MrBurmark -- Thank you!!

**Pull request merged**
