### PR TITLE
Pull release stuff into develop

### PR DESCRIPTION
**Pull request by rhornung67**

### CODE REVIEW

**Comment by davidbeckingsale** [comment]
This has conflicts....

**Comment by rhornung67** [comment]
The merge will update the blt submodule. How do I resolve this?

**Comment by jonesholger** [comment]
wait I thought you wanted to be at 599 wrt blt

diff --git a/blt b/blt
index 9d0069b..5994650 160000
--- a/blt
+++ b/blt
@@ -1 +1 @@
-Subproject commit 9d0069b947ea782226b608aceb8e002d0c47d18e
+Subproject commit 5994650a08a57b1598d795ee5886bcf29c253bbb

**Comment by rhornung67** [comment]
@jonesholger I do. develop branch has 9d0069b... master has 5994650a...  

I don't understand this conflict, nor how to resolve it. I'm trying some things now....

**Pull request closed without merging**
