### PR TITLE
Update a few things in the GItLab CI for consistency with RAJA

### PR DESCRIPTION
**Pull request by rhornung67**
# Summary (Write a short headline summary of PR)

- This PR includes some minor modifications to make GItLab CI more closely aligned with RAJA CI

### CODE REVIEW

**Comment by rhornung67** [comment]
@adrienbernede thank you for the fixes

**Comment by adrienbernede** [comment]
@rhornung67 Now passing. ;)

**Comment by rhornung67** [comment]
@adrienbernede if you approve, I will merge it!

**Comment by rhornung67** [comment]
@MrBurmark @artv3 @rchen20 this is good to merge. can i get an approval? thank you

**Review by adrienbernede — APPROVED** [review]

**Pull request merged**
