### PR TITLE
Optionally output npasses min,max,ave timing

### PR DESCRIPTION
**Pull request by MrBurmark**
# Add option to output min and max as well as average

Have the option to output the min, max, and/or average of
timing data using --npasses-combiner argument. Timing and speedup
csv files append the combiner method to their filename and print
the combiner method in the file.

- This PR is a feature
- It does the following:
  - Adds (specific feature) at the request of (project or person)

### CODE REVIEW

**Comment by artv3** [comment]
Just a though, but for MPI I know caliper can provide this information. One option could be to rely on caliper for more detailed timing info.

**Comment by MrBurmark** [comment]
We're already collecting this info, we just weren't outputting it. I agree caliper really is the place for more detailed stats.

**Review by rhornung67 — APPROVED** [review]
@MrBurmark I'm OK with this. Do you want to merge it?

**Comment by MrBurmark** [comment]
Sure, I'll merge it.
If we decide to do something more complicated for MPI later then we can figure out how to combine multi-pass with multi-rank data at that time.

**Pull request merged**
