### PR TITLE
Feature/rhornung67/newkernels

### PR DESCRIPTION
**Pull request by rhornung67**
PR to coordinate with openmp target merge.  Note: kernel modifications and additions are still a WIP here.

### CODE REVIEW

**Comment by jonesholger** [comment]
Initial merge looks good.  I've folded in show-progress, which incidentally the help text just needs a minor tweak (--show-progress vs show_progress). So, I'll gen omp-target implementations for the 3 new kernels, do some cleanup,  and set the rep_runs in REDUCE3_INT to a very low number,  otherwise the suite will look like it hangs (due to omp-target reduction performance).

**Comment by rhornung67** [comment]
@jonesholger please approve so I can merge

**Comment by rhornung67** [comment]
@jonesholger I pushed a fix to the help message for the show progress issue that you pointed out.  Can I get a re-approval? I'll merge this and start reviewing your PR. Thanks.

**Comment by rhornung67** [comment]
@jonesholger I need re-approval for pushing the fix for the show progress option.  Thanks.

**Comment by rhornung67** [comment]
Thanks @jonesholger !

**Pull request merged**
