### PR TITLE
Fix bugs in MPI usage

### PR DESCRIPTION
**Pull request by MrBurmark**
# Fix bugs in MPI usage

Fix hang where rank 0 did not enter a barrier if no path was given when creating directories.
Support long double with all reduce even if the MPI implementation lackes support for long double.
Fix prints to be rank 0 only.

- This PR is a bugfix
- It does the following (modify list as needed):
  - Fixes various things

### CODE REVIEW

**Review by rhornung67 — DISMISSED** [review]
Looks good. I haven't tried it out. I trust you.

**Comment by MrBurmark** [comment]
According to the testing your faith is misplaced.

**Comment by rhornung67** [comment]
> According to the testing your faith is misplaced.

I made the comment before I looked at the checks 😄

**Review by rhornung67 — APPROVED** [review]
Ahhhh. Much better.

**Pull request merged**
