### PR TITLE
Use coarse grained hip pinned memory

### PR DESCRIPTION
**Pull request by MrBurmark**
# Use coarse grained hip pinned memory

Use coarse grained hip pinned memory in reducers and fused kernels.
This improves performance as it can be cached on device

- This PR is a feature
- It does the following:
  - Adds more spped at the request of me

### CODE REVIEW

**Comment by rhornung67** [comment]
@MrBurmark working on RAJA + CI updates here: https://github.com/LLNL/RAJAPerf/pull/386

I broke something. Not sure what yet. When it's working and merged, you can update this PR.

**Comment by rhornung67** [comment]
@MrBurmark Did you intend to use coarse-grain pinned memory for *all* kernels with reductions?

**Comment by MrBurmark** [comment]
@rhornung67 Yes, I want to use coarse grained pinned memory for all reductions.

**Comment by rhornung67** [comment]
> @rhornung67 Yes, I want to use coarse grained pinned memory for all reductions.

So, we should make similar changes to PI_REDUCE, REDUCE_STRUCT, TRAP_INT, FIRST_MIN, and DOT, right?

**Comment by MrBurmark** [comment]
You'd think, but they use explicit memory copies instead of pinned memory. They should probably be changed to use pinned memory if possible.

**Review by rhornung67 — APPROVED** [review]
@MrBurmark this should be good to merge if you want the honor.

**Pull request merged**
