### PR TITLE
fix to data mapping in OpenMP target version of TRAP_INT kernel

### PR DESCRIPTION
**Pull request by mcordery**
Fixes a data mapping problem in TRAP_INT-OMPTarget where a data environment is created via

#pragma target  data map

rather than an async mapping via

#pragma target enter data map

This causes a failure at the subsequent exit data map. Fixed the mapping to use the  target
enter data map and kernel runs fine.

### CODE REVIEW

**Comment by dmcdougall** [comment]
This patch fixes the same problem for me as well.

**Comment by dmcdougall** [comment]
Is there any update on this PR?

**Comment by dmcdougall** [comment]
Another gentle ping :)

**Comment by davidbeckingsale** [comment]
Thanks for the reminder @dmcdougall

**Pull request merged**
